controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix:
        en: '/en'
        fr: '/fr'
    requirements:
        _locale: "%app.supported_locales%"
    defaults:
        _locale: "%app.default_locale%"


kernel:
    resource: ../../src/Kernel.php
    type: annotation
